Menu:
  Home: /
  Archives: /archives/
  About: /About/
  Github: https://github.com/garyyy-design/
  RSS: /atom.xml
  Search: true
  
Site:
  Motto: Be stronger than you really are

Intro:
  Avastar: 
  Name: 朱悦
  Brief: 浙江理工大学工业设计本科
  SNS: 
    Weibo:  
    StackOverflow: 
    Github: https://github.com/garyyy-design/
    Pinterest: 
    Quora: 

CopyRight: 
  Author: Sōsuke
  License: CC BY-NC-SA 3.0 CN

Tip:
  Alipay: /img/qrcode.jpeg
  Wechat: /img/qrcode.jpeg

Comment:
  Id: 8d83609a651e972e308d
  Secret: 37e40c89a47e957f654e86f71c5caaccad0774de
  Repo: Vevlins.github.io
  Owner: Vevlins

  jsonContent:
    meta: false
    pages: false
    posts:
        title: true
        date: true
        path: true
        text: true
        raw: false
        content: false
        slug: false
        updated: false
        comments: false
        link: false
        permalink: false
        excerpt: false
        categories: false
        tags: false