Menu:
  Home: /
  Archives: /archives/
  About: /About/
  Github: https://github.com/garyyy-design/
  RSS: /atom.xml
  Search: true
  
Site:
  Motto: Be stronger than you really are

Intro:
  
  Name: 朱悦
  Brief: 浙江理工大学工业设计本科
  SNS: 
     
  
    Github: https://github.com/garyyy-design/
  

CopyRight: 
  Author: 朱悦
  

Tip:
  Wechat: 

Comment:
  

  jsonContent:
    meta: false
    pages: false
    posts:
        title: true
        date: true
        path: true
        text: true
        raw: false
        content: false
        slug: false
        updated: false
        comments: false
        link: false
        permalink: false
        excerpt: false
        categories: false
        tags: false